# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

---
- name: Ensure '/srv/www' directory
  become: true
  ansible.builtin.file:
    path: /srv/www
    state: directory
    owner: labadm
    group: labadm
