# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

---
- gather_facts: true
  hosts: core
  roles:
  - role: common
  - role: single-node-k0s
    vars:
      k0s_version: v1.33.4+k0s.0
      k0s_config_src: "../../../overlays/core/etc/k0s/k0s.yaml"
      k0s_address: "{{ ansible_default_ipv4.address }}"
