# SPDX-FileCopyrightText: 2025 NONE
#
# SPDX-License-Identifier: Unlicense

---
- name: Download k0s binary
  become: true
  ansible.builtin.get_url:
    url: "https://github.com/k0sproject/k0s/releases/download/{{ k0s_version }}/k0s-{{ k0s_version }}-amd64"
    dest: /usr/local/bin/k0s-{{ k0s_version }}
    mode: '0750'
    owner: root
    group: root

- name: Create k0s symlink
  become: true
  ansible.builtin.file:
    src: /usr/local/bin/k0s-{{ k0s_version }}
    dest: /usr/local/bin/k0s
    state: link
    owner: root
    group: root
  notify: Restart k0scontroller

- name: Ensure '/etc/k0s' directory
  become: true
  ansible.builtin.file:
    path: /etc/k0s
    state: directory
    mode: '0755'

- name: Apply k0s configuration
  become: true
  ansible.builtin.template:
    src: "{{ k0s_config_src }}"
    dest: /etc/k0s/k0s.yaml
    mode: '0600'
  vars:
    address: "{{ k0s_address }}"
  notify: Restart k0scontroller
  when: k0s_config_src is defined
